# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import SpeechDevelopmentTest.protos.storage.storage_pb2 as storage__pb2


class StorageStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetQuestions = channel.unary_unary(
                '/protos.Storage/GetQuestions',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=storage__pb2.GetQuestionsResponse.FromString,
                )
        self.StartAttempt = channel.unary_unary(
                '/protos.Storage/StartAttempt',
                request_serializer=storage__pb2.StartAttemptRequest.SerializeToString,
                response_deserializer=storage__pb2.StartAttemptResponse.FromString,
                )
        self.UploadAudio = channel.unary_unary(
                '/protos.Storage/UploadAudio',
                request_serializer=storage__pb2.UploadAudioRequest.SerializeToString,
                response_deserializer=storage__pb2.UploadAudioResponse.FromString,
                )
        self.AttachReportToAttempt = channel.unary_unary(
                '/protos.Storage/AttachReportToAttempt',
                request_serializer=storage__pb2.AttachReportToAttemptRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetReportByAttempt = channel.unary_unary(
                '/protos.Storage/GetReportByAttempt',
                request_serializer=storage__pb2.GetReportByAttemptRequest.SerializeToString,
                response_deserializer=storage__pb2.GetReportByAttemptResponse.FromString,
                )
        self.GetAudiousInArchive = channel.unary_unary(
                '/protos.Storage/GetAudiousInArchive',
                request_serializer=storage__pb2.GetAudiousInArchiveRequest.SerializeToString,
                response_deserializer=storage__pb2.GetAudiousInArchiveResponse.FromString,
                )


class StorageServicer(object):
    """The greeting service definition.
    """

    def GetQuestions(self, request, context):
        """rpc GetReportsByUserId(GetReportsByUserIdRequest) returns (GetReportsByUserIdResponse);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartAttempt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AttachReportToAttempt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReportByAttempt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAudiousInArchive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetQuestions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQuestions,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=storage__pb2.GetQuestionsResponse.SerializeToString,
            ),
            'StartAttempt': grpc.unary_unary_rpc_method_handler(
                    servicer.StartAttempt,
                    request_deserializer=storage__pb2.StartAttemptRequest.FromString,
                    response_serializer=storage__pb2.StartAttemptResponse.SerializeToString,
            ),
            'UploadAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadAudio,
                    request_deserializer=storage__pb2.UploadAudioRequest.FromString,
                    response_serializer=storage__pb2.UploadAudioResponse.SerializeToString,
            ),
            'AttachReportToAttempt': grpc.unary_unary_rpc_method_handler(
                    servicer.AttachReportToAttempt,
                    request_deserializer=storage__pb2.AttachReportToAttemptRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetReportByAttempt': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReportByAttempt,
                    request_deserializer=storage__pb2.GetReportByAttemptRequest.FromString,
                    response_serializer=storage__pb2.GetReportByAttemptResponse.SerializeToString,
            ),
            'GetAudiousInArchive': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAudiousInArchive,
                    request_deserializer=storage__pb2.GetAudiousInArchiveRequest.FromString,
                    response_serializer=storage__pb2.GetAudiousInArchiveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.Storage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Storage(object):
    """The greeting service definition.
    """

    @staticmethod
    def GetQuestions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Storage/GetQuestions',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            storage__pb2.GetQuestionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartAttempt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Storage/StartAttempt',
            storage__pb2.StartAttemptRequest.SerializeToString,
            storage__pb2.StartAttemptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Storage/UploadAudio',
            storage__pb2.UploadAudioRequest.SerializeToString,
            storage__pb2.UploadAudioResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AttachReportToAttempt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Storage/AttachReportToAttempt',
            storage__pb2.AttachReportToAttemptRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetReportByAttempt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Storage/GetReportByAttempt',
            storage__pb2.GetReportByAttemptRequest.SerializeToString,
            storage__pb2.GetReportByAttemptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAudiousInArchive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Storage/GetAudiousInArchive',
            storage__pb2.GetAudiousInArchiveRequest.SerializeToString,
            storage__pb2.GetAudiousInArchiveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
